# Generated by Django 5.1.6 on 2025-02-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_image', to='catalog.image'),
        ),
    ]
